### ISSUE TITLE
create errors when selecting application and vue

### ISSUE THREAD

**Issue by slanted** [single-spa/create-single-spa#18]
steps to replicate:
- install latest version globally
- make new dir and cd into it
- >create-single-spa
? Select type to generate single-spa application / parcel
? Which framework do you want to use? vue
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn vue ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn vue',
  path: 'vue',
  spawnargs: [ 'create', '.' ]
}

node -v shows
v12.14.0

Hope thats enough.

Regards,
Eric

**Comment by joeldenning** [comment]
Hi Eric - I've transferred this issue over to the create-single-spa repository.

The error is because create-single-spa assumes that vue cli is installed globally. I went back and forth on whether I should assume vue cli is installed or not globally. I'll take this issue as a hint that that's a bad assumption. Will update the project to work without global vue installation.

**Comment by joeldenning** [comment]
This will be fixed in https://github.com/single-spa/create-single-spa/pull/19.
