### ISSUE TITLE
Install create-single-spa fails

### ISSUE THREAD

**Issue by kroissma** [single-spa/create-single-spa#249]
Hi,

I just tried to install create-single-spa:

```
$ npm install --global create-single-spa
```

This resulted in the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for generator-single-spa@^2.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'create-single-spa'
npm ERR! notarget
```

Seems like generator-single-spa@^2.0.0 is not available at the npm registry.

Here the full log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'create-single-spa'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v15.3.0
4 verbose npm-session 39471dcaca5c85fd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/create-single-spa 15ms (from cache)
8 silly pacote tag manifest for create-single-spa@latest fetched in 33ms
9 timing stage:loadCurrentTree Completed in 103ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule create-single-spa@2.0.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/generator-single-spa 457ms
18 silly fetchPackageMetaData error for generator-single-spa@^2.0.0 No matching version found for generator-single-spa@^2.0.0.
19 http fetch GET 304 https://registry.npmjs.org/yeoman-environment 463ms (from cache)
20 silly pacote range manifest for yeoman-environment@^2.10.3 fetched in 467ms
21 silly resolveWithNewModule yeoman-environment@2.10.3 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/yargs 469ms (from cache)
23 silly pacote range manifest for yargs@^16.2.0 fetched in 474ms
24 silly resolveWithNewModule yargs@16.2.0 checking installable status
25 timing stage:rollbackFailedOptional Completed in 0ms
26 timing stage:runTopLevelLifecycles Completed in 587ms
27 verbose type range
28 verbose stack generator-single-spa: No matching version found for generator-single-spa@^2.0.0.
28 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
28 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
28 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
28 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
28 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
28 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
28 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
28 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
28 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
28 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
28 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
28 verbose stack     at processImmediate (node:internal/timers:463:21)
29 verbose cwd /mnt/Daten/Programmieren/Masterarbeit
30 verbose Linux 5.4.0-62-generic
31 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "create-single-spa"
32 verbose node v15.3.0
33 verbose npm  v6.14.9
34 error code ETARGET
35 error notarget No matching version found for generator-single-spa@^2.0.0.
36 error notarget In most cases you or one of your dependencies are requesting
36 error notarget a package version that doesn't exist.
36 error notarget
36 error notarget It was specified as a dependency of 'create-single-spa'
37 verbose exit [ 1, true ]

```

**Comment by joeldenning** [comment]
This is now fixed - the publish of 2.0.0 didn't happen for generator-single-spa, so I published it now.
