### ISSUE TITLE
Throwing error while creating single spa angular app

### ISSUE THREAD

**Issue by cah-nagaraj-vemula** [single-spa/create-single-spa#342]
I tried adding single spa angular 5.0.2 with create-single-spa command and I got follwoing error

[error] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/nagaraj.vemula/service/ng-app/ng-single-spa-app/node_modules/@angular/core/fesm2015/core.mjs
    at Module.load (internal/modules/cjs/loader.js:948:11)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/nagaraj.vemula/service/ng-app/ng-single-spa-app/node_modules/single-spa-angular/schematics/ng-add/rules/add-dependencies.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)

ng --version

    

Angular CLI: 13.0.3
Node: 14.17.1
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4

**Comment by filoxo** [comment]
Support for Angular 13 is still WIP. This issue is documented here https://github.com/single-spa/single-spa-angular/pull/405
I'm closing this issue because it isn't directly related to the code shipped by create-single-spa though there are likely changes to be made to limit the version of angular able to be used with create-single-spa.
