### ISSUE TITLE
Issues with local setup

### ISSUE THREAD

**Issue by lipsumar** [single-spa/create-single-spa#343]
We're starting to use single-spa's SSR in production. So far it's working great!

We had a custom import-map fetcher and recently found out about `getImportMaps` and the `single-spa-web-server-utils` package. I'm happy to say this package works well with a Typescript setup, we just had to switch to ESM and got closer to the future!

We found a few issues with `getImportMaps`:
- it leaks during tests: a `setInterval` is setup without any mean to cancel it;
- error handling seems a bit harsh, where a single fail to fetch the import map would crash the server (as i understand it).

We would like to PR some changes to improve these points. Unfortunately it seems the "out of the box" clone of this repo doesn't work properly on my machine:
- can't run tests
- can't "upgrade dependencies"

Following the [contributing guide](https://github.com/single-spa/create-single-spa/blob/main/CONTRIBUTING.md), I did the following steps:

1. `git clone git@github.com:single-spa/create-single-spa.git`
2. `cd create-single-spa`
3. `pnpm install`
4. `pnpm test --recursive`

The test fails with the following output:

```
Scope: all 10 workspace projects
. test$ pnpm run clean-tests && pnpm run test:e2e
[6 lines collapsed]
│ . prepare: husky - Git hooks installed
│ . prepare: Done
│ > root@ test:e2e /private/tmp/create-single-spa
│ > jest
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Creating 'root-config-ts-webpack' fixture.
│ node ../../packages/create-single-spa/bin/create-single-spa.js --dir root-config-ts-webpack 
└─ Running...
packages/single-spa-web-server-utils test$ echo "Error: run tests from root" && exit 0
│ Error: run tests from root
└─ Done in 20ms
packages/generator-single-spa test$ jest
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ Browserslist: caniuse-lite is outdated. Please run:
│ npx browserslist@latest --update-db
│ Why you should do it regularly:
│ https://github.com/browserslist/browserslist#browsers-data-updating
│ PASS test/validate-naming.test.js
│ PASS test/version-update-check.test.js
│ FAIL test/basic.test.js (14.124 s)
│   ● generator-single-spa › can run the generator
│     thrown: "Exceeded timeout of 5000 ms for a test.
│     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running
│       3 |
│       4 | describe("generator-single-spa", () => {
│     > 5 |   it("can run the generator", async () => {
│         |   ^
│       6 |     const runResult = await helpers
│       7 |       .create(generator)
│       8 |       .withOptions({
│       at test/basic.test.js:5:3
│       at Object.<anonymous> (test/basic.test.js:4:1)
│ FAIL test/root-config.test.js (14.13 s)
│   ● generator-single-spa › can run the generator
│     thrown: "Exceeded timeout of 5000 ms for a test.
│     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running
│       3 |
│       4 | describe("generator-single-spa", () => {
│     > 5 |   it("can run the generator", async () => {
│         |   ^
│       6 |     const runResult = await helpers
│       7 |       .create(generator)
│       8 |       .withOptions({
│       at test/root-config.test.js:5:3
│       at Object.<anonymous> (test/root-config.test.js:4:1)
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at AsyncFunction.Object.<anonymous>.module.exports.sync (../../node_modules/.pnpm/read
│       at AsyncFunction.Object.<anonymous>.module.exports.sync (../../node_modules/.pnpm/read
│       at SingleSpaRootConfigGenerator.rootGeneratorName (../../node_modules/.pnpm/yeoman-gen
│       at SingleSpaRootConfigGenerator._getGlobalStorage (../../node_modules/.pnpm/yeoman-gen
│       at new Generator (../../node_modules/.pnpm/yeoman-generator@5.4.2/node_modules/yeoman-
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at AsyncFunction.Object.<anonymous>.module.exports.sync (../../node_modules/.pnpm/read
│       at AsyncFunction.Object.<anonymous>.module.exports.sync (../../node_modules/.pnpm/read
│       at SingleSpaReactGenerator.rootGeneratorName (../../node_modules/.pnpm/yeoman-generato
│       at SingleSpaReactGenerator._getGlobalStorage (../../node_modules/.pnpm/yeoman-generato
│       at new Generator (../../node_modules/.pnpm/yeoman-generator@5.4.2/node_modules/yeoman-
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ ReferenceError: You are trying to `import` a file after the Jest environment has been torn d
│       at Function.promptModule.restoreDefaultPrompts (../../node_modules/.pnpm/inquirer@8.1.
│       at YeomanTest.Object.<anonymous>.YeomanTest.restorePrompt (../../node_modules/.pnpm/ye
│       at ../../node_modules/.pnpm/yeoman-test@6.2.0_yeoman-generator@5.4.2/node_modules/yeom
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Reinitialized existing Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh000
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Reinitialized existing Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh000
│ Reinitialized existing Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh000
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ hint: Using 'master' as the name for the initial branch. This default branch name
│ hint: is subject to change. To configure the initial branch name to use in all
│ hint: of your new repositories, which will suppress this warning, call:
│ hint: 
│ hint: 	git config --global init.defaultBranch <name>
│ hint: 
│ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
│ hint: 'development'. The just-created branch can be renamed via this command:
│ hint: 
│ hint: 	git branch -m <name>
│ FAIL test/svelte.test.js (24.195 s)
│   ● Console
│     console.log
│       
│       Initialized git repository
│       at SingleSpaSvelteGenerator.copyOtherFiles (src/svelte/generator-single-spa-svelte.js:
│     console.log
│       
│       Initialized git repository
│       at SingleSpaSvelteGenerator.copyOtherFiles (src/svelte/generator-single-spa-svelte.js:
│     console.log
│       
│       Initialized git repository
│       at SingleSpaSvelteGenerator.copyOtherFiles (src/svelte/generator-single-spa-svelte.js:
│     console.log
│       
│       Initialized git repository
│       at SingleSpaSvelteGenerator.copyOtherFiles (src/svelte/generator-single-spa-svelte.js:
│   ● generator-single-spa-svelte › handles yarn option properly
│     thrown: "Exceeded timeout of 5000 ms for a test.
│     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running
│       18 |       .run();
│       19 |
│     > 20 |   it("handles yarn option properly", async () => {
│          |   ^
│       21 |     const runResult = await runWithPrompts({ packageManager: "yarn" });
│       22 |     runResult.assertFile("package.json");
│       23 |   });
│       at test/svelte.test.js:20:3
│       at Object.<anonymous> (test/svelte.test.js:4:1)
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ Initialized empty Git repository in /private/var/folders/hm/kz9nt_ns2l7d7y85y3b8k4rh0000gp/T
│ FAIL test/util-module.test.js (24.231 s)
│   ● Console
│     console.log
│       
│       Initialized git repository
│       at SingleSpaUtilModuleGenerator.copyOtherFiles (src/util-module/generator-single-spa-u
│     console.log
│       
│       Initialized git repository
│       at SingleSpaUtilModuleGenerator.copyOtherFiles (src/util-module/generator-single-spa-u
│     console.log
│       
│       Initialized git repository
│       at SingleSpaUtilModuleGenerator.copyOtherFiles (src/util-module/generator-single-spa-u
│     console.log
│       
│       Initialized git repository
│       at SingleSpaUtilModuleGenerator.copyOtherFiles (src/util-module/generator-single-spa-u
│   ● generator-single-spa-util-module › handles yarn option properly
│     thrown: "Exceeded timeout of 5000 ms for a test.
│     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running
│       19 |       .run();
│       20 |
│     > 21 |   it("handles yarn option properly", async () => {
│          |   ^
│       22 |     const runResult = await generateRunContext({ packageManager: "yarn" });
│       23 |     runResult.assertFile("package.json");
│       24 |   });
│       at test/util-module.test.js:21:3
│       at Object.<anonymous> (test/util-module.test.js:4:1)
│ FAIL test/react.test.js (24.892 s)
│   ● Console
│     console.log
│       
│       Initialized git repository
│       at SingleSpaReactGenerator.copyOtherFiles (src/react/generator-single-spa-react.js:210
│     console.log
│       
│       Initialized git repository
│       at SingleSpaReactGenerator.copyOtherFiles (src/react/generator-single-spa-react.js:210
│     console.log
│       
│       Initialized git repository
│       at SingleSpaReactGenerator.copyOtherFiles (src/react/generator-single-spa-react.js:210
│     console.log
│       
│       Initialized git repository
│       at SingleSpaReactGenerator.copyOtherFiles (src/react/generator-single-spa-react.js:210
│   ● generator-single-spa-react › handles yarn option properly
│     thrown: "Exceeded timeout of 5000 ms for a test.
│     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running
│       18 |       .run();
│       19 |
│     > 20 |   it("handles yarn option properly", async () => {
│          |   ^
│       21 |     const runResult = await runGenerator({
│       22 |       packageManager: "yarn",
│       23 |     });
│       at test/react.test.js:20:3
│       at Object.<anonymous> (test/react.test.js:4:1)
│ Test Suites: 5 failed, 2 passed, 7 total
│ Tests:       5 failed, 19 passed, 24 total
│ Snapshots:   0 total
│ Time:        26.139 s
│ Ran all test suites.
└─ Failed in 29.1s
/private/tmp/create-single-spa/packages/generator-single-spa:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  generator-single-spa@4.1.2 test: `jest`
Exit status 1
```

I then tried to follow the steps under "Upgrading dependencies" by running `./scripts/upgrade-dependencies.sh`. I got the following output:

```
✔ Install the following package: ncu@latest? (Y/n) · true
 WARN  deprecated ncu@0.2.1: This package has been deprecated, and this is not npm-check-updates
Packages: +76
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/emmanuelpire/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 76, reused 48, downloaded 28, added 76, done

/Users/emmanuelpire/.pnpm-store/v3/tmp/_npx/64537/5:
+ ncu 0.2.1 deprecated
NCU Real Time Weather is Running......
2021/11/30 14:55 Tuesday UTC+8:00

Whoops! The program is outdate, cann't get things from http://pblap.atm.ncu.edu.tw

✔ Install the following package: ncu@latest? (Y/n)
```
As you can see, this is looping, always asking me if i want to install `ncu@latest` - which is deprecated.

I don't understand even why we would want to install [`ncu`](https://www.npmjs.com/package/ncu), a deprecated package intended to fetch weather data.

What makes more sense is that this script means to use `npm-check-updates`, whose cli command is `ncu`. I'll see if i can already make a PR to fix this.

My setup:
- node `v16.4.2`
- pnpm `6.23.2`
- Mac OSX `11.6`

**Comment by lipsumar** [comment]
I figured out the `ncu` issue and made a PR: https://github.com/single-spa/create-single-spa/pull/344

**Comment by joeldenning** [comment]
Thanks for #344, I created some tests and fixes for single-spa-web-server-utils in #347 to address the two issues you brought up. Will document it soon. Landed in single-spa-web-server-utils@2.3.0, release notes at https://github.com/single-spa/create-single-spa/blob/main/packages/single-spa-web-server-utils/CHANGELOG.md#230

**Comment by joeldenning** [comment]
Documented in https://github.com/single-spa/single-spa.js.org/pull/526

**Comment by joeldenning** [comment]
Documentation is live at https://single-spa.js.org/docs/create-single-spa/#clearallintervals and https://single-spa.js.org/docs/create-single-spa/#reset
