### ISSUE TITLE
`name` parameter from missing from package.json

### ISSUE THREAD

**Issue by brandones** [single-spa/create-single-spa#50]
Repro by adding another "option" parameter to SingleSpaReactGenerator: https://github.com/brandones/create-single-spa/tree/name-repro

Causes AssertionError: `A name parameter is required to create a storage`

See https://github.com/iotacss/iotaplate/issues/1

```
../create-single-spa/packages/create-single-spa/bin/create-single-spa.js
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: A name parameter is required to create a storage
    at new Storage (/home/brandon/Code/pih/mf/create-single-spa/packages/generator-single-spa/node_modules/yeoman-generator/lib/util/storage.js:24:5)
    at SingleSpaGenerator._getStorage (/home/brandon/Code/pih/mf/create-single-spa/packages/generator-single-spa/node_modules/yeoman-generator/lib/index.js:655:12)
    at new Generator (/home/brandon/Code/pih/mf/create-single-spa/packages/generator-single-spa/node_modules/yeoman-generator/lib/index.js:153:24)
    at new SingleSpaGenerator (/home/brandon/Code/pih/mf/create-single-spa/packages/generator-single-spa/src/generator-single-spa.js:10:5)
    at Environment.instantiate (/home/brandon/Code/pih/mf/create-single-spa/packages/create-single-spa/node_modules/yeoman-environment/lib/environment.js:516:12)
    at Environment.create (/home/brandon/Code/pih/mf/create-single-spa/packages/create-single-spa/node_modules/yeoman-environment/lib/environment.js:494:17)
    at Environment.run (/home/brandon/Code/pih/mf/create-single-spa/packages/create-single-spa/node_modules/yeoman-environment/lib/environment.js:551:28)
    at Object.<anonymous> (/home/brandon/Code/pih/mf/create-single-spa/packages/create-single-spa/bin/create-single-spa.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by brandones** [comment]
Yeoman doesn't hit this error if I add a `default` to the option. Should probably open a bug on Yeoman. Closing this.
