### ISSUE TITLE
Failed to compile because generator does not produce a src directory

### ISSUE THREAD

**Issue by protoEvangelion** [single-spa/create-single-spa#70]
The generator is failing to produce applications that compile.  The issue looks like that there is no `/lib/node_modules/create-single-spa/node_modules` folder. 

![image](https://user-images.githubusercontent.com/20076677/78903624-430a7880-7a30-11ea-9487-e706a61fe724.png)

Maybe this has to do with the fact that I'm using [n](https://github.com/tj/n) on a mac to manage node versions?

Here is the output from running the generator:

```
 ~/dev/monorepo| => create-single-spa
? Select type to generate single-spa application / parcel
? Which framework do you want to use? react
? Which package manager do you want to use? yarn
? Will this project use Typescript? No
? Organization name (use lowercase and dashes) tio
? Project name (use lowercase and dashes) lumin
(node:14692) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/rgarant/n/lib/node_modules/create-single-spa/node_modules/generator-single-spa/src/common-templates/.gitignore
    at EditionInterface.exports.copy (/Users/rgarant/n/lib/node_modules/create-single-spa/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/rgarant/n/lib/node_modules/create-single-spa/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at SingleSpaReactGenerator.copyOtherFiles (/Users/rgarant/n/lib/node_modules/create-single-spa/node_modules/generator-single-spa/src/react/generator-single-spa-react.js:108:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
   create package.json
   create jest.config.js
   create .babelrc
   create .eslintrc
```

Yarn succeeds & then I run the start cmd: `yarn start --https --port 8500`

```
ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/rgarant/dev/monorepo'

ERROR in multi (webpack)-dev-server/client?https://localhost:8500 ./src
Module not found: Error: Can't resolve './src' in '/Users/rgarant/dev/monorepo'
 @ multi (webpack)-dev-server/client?https://localhost:8500 ./src main[1]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by TheMcMurder** [comment]
This seems related to my change in: #65 I'm debugging. It's odd because my changes worked locally but apparently not in the deployed module

**Comment by joeldenning** [comment]
The fix from @TheMcMurder is now released in https://github.com/single-spa/create-single-spa/releases/tag/v1.4.2. Let us know if you still see any problems with 1.4.2

**Comment by protoEvangelion** [comment]
@TheMcMurder confirmed that is working. Thanks for the quick patch!
